### ISSUE TITLE
Just errors

### ISSUE THREAD

**Issue by Guenni75** [ogra1/mjpg-streamer#1]
Hi.
I only get:

501: Not Implemented!
no www-folder configured

I can't find a manual or something like that how to configure this.

**Comment by lukeallister** [comment]
I also get this error and cannot use it.

**Comment by lukeallister** [comment]
Update: I was able to get a workaround after reading  through the source to see what the default "-w ./www" flag was pointing to. I manually set that to "/snap/mjpg-streamer/current/share/mjpg-streamer/www" and it now works. 

Full command for me: `mjpg-streamer -i "input_uvc.so" -o "output_http.so -w /snap/mjpg-streamer/current/share/mjpg-streamer/www"`

I think this is an issue with the paths setup automatically in the `/snap/mjpg-streamer/current/bin/mjpg-streamer.sh` file

**Comment by ogra1** [comment]
It is intentional that if you do not use the included daemon you are free to use i.e. ~/snap/mjpg-streamer/current/www to ship your own websites so -w *must* be explicitly provided in "manual mode" (Note that you can always use "http://&lt;YOUR_IP&gt;:&lt;PORT&gt;/?action=stream" to access the camera even without www dir).

If you use the daemon it will automatically create /var/snap/mjpg-streamer/current/www with the default website content that the app ships and use this.

To use the daemon, enable it in /var/snap/mjpg-streamer/current/config and run "snap restart mjpg-streamer" as described in "snap info mjpg-streamer" as well as on the package page at https://snapcraft.io/mjpg-streamer/

I will add a README.md here as well to make the intended functionality and snap specific bits more clear.

**Comment by lukeallister** [comment]
Thanks for clarifying; the README will definitely help.

**Comment by ogra1** [comment]
fixed with https://github.com/ogra1/mjpg-streamer/commit/9c15481abe69cb6cba002ce332bde47694319898
